DATABASE:
  host: localhost
  user: root
  password: 
  database: wall_assignment_november

SESSION_NAME: 'secret-session'
SERVER: localhost
PORT: 8088

ENCRYPTION:
  passkey:
    start: 'gha67432sdghag7s23_'
    end: '_ha8762bb'